# Generated by Django 3.2.4 on 2021-06-26 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='تگ')),
                ('status', models.CharField(choices=[('y', 'بله'), ('n', 'خیر')], default='y', max_length=1, verbose_name='آیا نمایش داده شود؟')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-position'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='موضوع')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='تگ')),
                ('description', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(upload_to='images', verbose_name='عکس')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='نوشته شده در تاریخ')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('status', models.CharField(choices=[('d', 'پیش نویش'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('category', models.ManyToManyField(related_name='articles', to='blog.Category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-publish'],
            },
        ),
    ]
